#!/bin/bash   
#PATH_TO_BIN="/home/pi/repo/aquaponics.git/sensors/"
#STR="Starting the water level probe..."
#echo $STR
#cd $PATH_TO_BIN
echo "Starting multitail of log files..."
echo "Start temp"
sudo t > /var/log/temperature.log &
echo "Start water level"
sudo f > /var/log/water_level.log &
multitail -f /var/log/temperature.log -f /var/log/water_level.log

